name: dino_lab
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  auto_route: ^9.2.2
  data:
    path: ./packages/data
  domain:
    path: ./packages/domain
  shared:
    path: ./packages/shared
  rxdart: ^0.28.0
  mocktail: ^1.0.4
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
